### PR TITLE
SOAP fixes

### PR DESCRIPTION
**Pull request by slafs**
Hello

I know you'll reject this in favor of using openstack-gerrit
but I found several minor bugs in the SOAP protocol that I tried to fix in this PR.

I'll just leave this here :)

### CODE REVIEW

**Comment by cdevienne** [comment]
Hi @slafs 

I would like to merge your changes. The really simple way is for you to push them on gerrit, so they can go through the standard reviewing process.

Any other option would remove you as the author of the cset (you would still have credit in the commit message though), which I want to avoid.

Thanks,

Christophe

**Comment by slafs** [comment]
Hi @cdevienne 

Would love this. But can you elaborate a bit on this:

> The really simple way is for you to push them on gerrit

The gerrit link in README doesn't seem to work (https://review.openstack.org/#/q/project:stackforge/wsme,n,z/) so I'm little confused about what I really should do.

**Comment by cdevienne** [comment]
The 'simple way' is actually simple for me, and make sure the csets are pushed as they are in the repo.

The thing is that gerrit will not allow me to propose your csets for review. So either I change them to be the author, either you submit them yourself.

To submit them, you have to register on https://review.openstack.org/ (The sign in link), set-up you ssh key, then install git-review (https://wiki.openstack.org/wiki/Gerrit_Workflow#Git_Review_Installation), and use it to push your changes to gerrit ("git review" instead of "git push", see 
https://wiki.openstack.org/wiki/Gerrit_Workflow#Project_Setup).

If you have questions don't hesitate. You can ask on irc on #wsme (freenode).

**Comment by slafs** [comment]
Done... I think. https://review.openstack.org/144956

It was hard to find the link for the project though ;)

**Comment by cdevienne** [comment]
The patch was reviewed and merged.

Thanks a lot !

**Comment by slafs** [comment]
Great! Any plans for a new release?

**Pull request closed without merging**
